inherit_from: ../../.rubocop.yml

Metrics/PerceivedComplexity:
  AllowedMethods:
    - call

Metrics/CyclomaticComplexity:
  AllowedMethods:
    - call

Metrics/AbcSize:
  AllowedMethods:
    - call

Lint/MissingSuper:
  Enabled: false
