#!/bin/bash

if [ "$SKIP_CHECKS" = "1" ]; then
  exit 0
fi

abort=false

dir=$(mktemp -d)

echo "Running Rubocop..."
bundle exec rubocop > "$dir/rubocop.txt"
if [ $? -ne 0 ]; then
  echo "Rubocop Errors. Check $dir/rubocop.txt"
  abort=true
fi

echo "Running RSpec..."
bundle exec rspec > "$dir/rspec.txt"
if [ $? -ne 0 ]; then
  echo "RSpec Errors. Check $dir/rspec.txt"
  abort=true
fi

if [ "$abort" = true ]; then
  echo '==========================='
  echo 'Aborting'
  exit 1
fi
